import random

def generate_sql(count=100):
    # Pre-calculated BCrypt hash for "password123"
    password_hash = "$2a$10$n9L0pCHoPbIdI/Vp8p.HEuehsh1u3B.5rI6G1P.gXz4C8s6Q9r.dy" 
    
    sql = "INSERT INTO users (username, email, password_hash, avatar_url, bio, role, is_verified) VALUES\n"
    
    values = []
    for i in range(1, count + 1):
        username = f"user_{i}"
        email = f"user{i}@ptitube.com"
        avatar_url = f"https://i.pravatar.cc/150?u={username}"
        bio = f"Hello, I am {username}. I love watching short videos on Ptitube!"
        role = "user"
        # Every 10th user is verified
        is_verified = "TRUE" if i % 10 == 0 else "FALSE"
        
        # Escape single quotes in bio if any (though there aren't in this fixed string)
        safe_bio = bio.replace("'", "''")
        
        values.append(f"('{username}', '{email}', '{password_hash}', '{avatar_url}', '{safe_bio}', '{role}', {is_verified})")
    
    sql += ",\n".join(values) + ";"
    return sql

if __name__ == "__main__":
    import os
    # Ensure current directory is correct or use relative path
    output_path = "database/seed_users.sql"
    
    # Check if we are in the root directory
    if not os.path.exists("database"):
        os.makedirs("database")
        
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- Seed users generated by generate_users.py\n")
        f.write(generate_sql(100))
    print(f"Generated {output_path}")
